on: [push] # push 代码时触发
jobs:
    deploy:
        runs-on: ubuntu-latest
        name: Tencent Cloudbase Github Action Example
        steps:
        - name: Checkout
          uses: actions/checkout@v2
        # 使用云开发 Github Action 部署
        - name: Deploy static to Tencent CloudBase
          id: deployStatic
          uses: TencentCloudBase/cloudbase-action@v2
          with:
            # 云开发的访问密钥 secretId 和 secretKey
            secretId: ${{ secrets.SECRET_ID }}
            secretKey: ${{ secrets.SECRET_KEY }}
            # 云开发的环境id
            envId: ${{ secrets.ENV_ID }}
            # Github 项目静态文件的路径
            staticSrcPath: docs/.vuepress/dist
            # 如需将静态资源部署到云端的某个子目录而非根目录，需要下面这个参数
            # staticDestPath: ./public
